object: orig/GXSE8P-Demo/sys/main.dol
hash: 453779ce4233091055877c408a15612b4cf39d3e
symbols: config/GXSE8P-Demo/symbols.txt
splits: config/GXSE8P-Demo/splits.txt
mw_comment_version: 10 # GC Linker 2.0

modules:
- name: Main
  object: orig/GXSE8P-Demo/files/_Main.rel
  hash: 54eed98a2dedea0a5857f7dbb85e02ef1c454093
  symbols: config/GXSE8P-Demo/rels/Main/symbols.txt
  splits: config/GXSE8P-Demo/rels/Main/splits.txt
- object: orig/GXSE8P-Demo/files/ModelsMiles.rel
  hash: a7f855ab9e2926ee5840a4c0d8239eaaf29774e6
  symbols: config/GXSE8P-Demo/rels/ModelsMiles/symbols.txt
  splits: config/GXSE8P-Demo/rels/ModelsMiles/splits.txt
- object: orig/GXSE8P-Demo/files/ModelsKnuckles.rel
  hash: 31a0928d91ea25e0116cc68c8467a53fd096550c
  symbols: config/GXSE8P-Demo/rels/ModelsKnuckles/symbols.txt
  splits: config/GXSE8P-Demo/rels/ModelsKnuckles/splits.txt
- object: orig/GXSE8P-Demo/files/Movie.rel
  hash: 8dd68256e1928604013aaf6e0d4875f4dc0c8bec
  symbols: config/GXSE8P-Demo/rels/Movie/symbols.txt
  splits: config/GXSE8P-Demo/rels/Movie/splits.txt
- name: Stg01
  object: orig/GXSE8P-Demo/files/_Stg01.rel
  hash: 79490aa0cd0638938ba44fbdd590e29517f216a0
  symbols: config/GXSE8P-Demo/rels/Stg01/symbols.txt
  splits: config/GXSE8P-Demo/rels/Stg01/splits.txt
- name: Stg02
  object: orig/GXSE8P-Demo/files/_Stg02.rel
  hash: cb62f1caba68ac7f02ef69a1428e222c5fc5eede
  symbols: config/GXSE8P-Demo/rels/Stg02/symbols.txt
  splits: config/GXSE8P-Demo/rels/Stg02/splits.txt
- name: Stg04
  object: orig/GXSE8P-Demo/files/_Stg04.rel
  hash: 73723ae1cccd15fbead6329fd2b584b0c6bccad8
  symbols: config/GXSE8P-Demo/rels/Stg04/symbols.txt
  splits: config/GXSE8P-Demo/rels/Stg04/splits.txt
- name: Stg05
  object: orig/GXSE8P-Demo/files/_Stg05.rel
  hash: ed941832c2f589de7f4e64b59854e2bbdd161bc2
  symbols: config/GXSE8P-Demo/rels/Stg05/symbols.txt
  splits: config/GXSE8P-Demo/rels/Stg05/splits.txt
- name: Stg08
  object: orig/GXSE8P-Demo/files/_Stg08.rel
  hash: 5ae960f4b1af5586d8b460007f804908b1c868b9
  symbols: config/GXSE8P-Demo/rels/Stg08/symbols.txt
  splits: config/GXSE8P-Demo/rels/Stg08/splits.txt
- name: Stg10
  object: orig/GXSE8P-Demo/files/_Stg10.rel
  hash: 9262910e4144713aabe2f473b19be85de1efab5a
  symbols: config/GXSE8P-Demo/rels/Stg10/symbols.txt
  splits: config/GXSE8P-Demo/rels/Stg10/splits.txt
- object: orig/GXSE8P-Demo/files/summary.rel
  hash: 2bb2bf00bfe99301a01dc8505bf16074fdec7020
  symbols: config/GXSE8P-Demo/rels/summary/symbols.txt
  splits: config/GXSE8P-Demo/rels/summary/splits.txt
- object: orig/GXSE8P-Demo/files/a_mot.rel
  hash: ba7dd5be6403dfe01f2e88037c20b56d8af368a6
  symbols: config/GXSE8P-Demo/rels/a_mot/symbols.txt
  splits: config/GXSE8P-Demo/rels/a_mot/splits.txt
- object: orig/GXSE8P-Demo/files/b_mot.rel
  hash: db0eddf9bff7283d13c27523cc10020c7f2feb36
  symbols: config/GXSE8P-Demo/rels/b_mot/symbols.txt
  splits: config/GXSE8P-Demo/rels/b_mot/splits.txt
- object: orig/GXSE8P-Demo/files/e_mot.rel
  hash: c21b6718432f7b5ff4c5d401ef61149d769adaa0
  symbols: config/GXSE8P-Demo/rels/e_mot/symbols.txt
  splits: config/GXSE8P-Demo/rels/e_mot/splits.txt
- object: orig/GXSE8P-Demo/files/k_mot.rel
  hash: 8546f786e7e7107c7b6737bdb4fd8e50d6f8b371
  symbols: config/GXSE8P-Demo/rels/k_mot/symbols.txt
  splits: config/GXSE8P-Demo/rels/k_mot/splits.txt
- object: orig/GXSE8P-Demo/files/s_mot.rel
  hash: b7a825350dabc05d64775e5f1a736fc437723c2d
  symbols: config/GXSE8P-Demo/rels/s_mot/symbols.txt
  splits: config/GXSE8P-Demo/rels/s_mot/splits.txt
- object: orig/GXSE8P-Demo/files/s_sbmot.rel
  hash: e2a6d368bdc0dab72385a34cfa086ae7318602a3
  symbols: config/GXSE8P-Demo/rels/s_sbmot/symbols.txt
  splits: config/GXSE8P-Demo/rels/s_sbmot/splits.txt
- object: orig/GXSE8P-Demo/files/m_sbmot.rel
  hash: 4f580aff9205a7ddf5df2390c50ea8410b24caf4
  symbols: config/GXSE8P-Demo/rels/m_sbmot/symbols.txt
  splits: config/GXSE8P-Demo/rels/m_sbmot/splits.txt
- object: orig/GXSE8P-Demo/files/Advertise.rel
  hash: 5396543d3176f9966eae54587295dd33b526e2f1
  symbols: config/GXSE8P-Demo/rels/Advertise/symbols.txt
  splits: config/GXSE8P-Demo/rels/Advertise/splits.txt
- object: orig/GXSE8P-Demo/files/alertwnd.rel
  hash: d9e63b83f8de1183dbe171fbe9096ef2a1d2e20f
  symbols: config/GXSE8P-Demo/rels/alertwnd/symbols.txt
  splits: config/GXSE8P-Demo/rels/alertwnd/splits.txt
