object: orig/GXSP8P-Demo/sys/main.dol
hash: 486003719668dd5a471b1d5a5839fb303cd86616
symbols: config/GXSP8P-Demo/symbols.txt
splits: config/GXSP8P-Demo/splits.txt
mw_comment_version: 10 # GC Linker 2.0

modules:
- name: Main
  object: orig/GXSP8P-Demo/files/_Main.rel
  hash: a57dba027f21dceae4c984a6e963ebb14ae7ec6e
  symbols: config/GXSP8P-Demo/rels/Main/symbols.txt
  splits: config/GXSP8P-Demo/rels/Main/splits.txt
- object: orig/GXSP8P-Demo/files/ModelsMiles.rel
  hash: a7f855ab9e2926ee5840a4c0d8239eaaf29774e6
  symbols: config/GXSP8P-Demo/rels/ModelsMiles/symbols.txt
  splits: config/GXSP8P-Demo/rels/ModelsMiles/splits.txt
- object: orig/GXSP8P-Demo/files/ModelsKnuckles.rel
  hash: 02b0ac1a4e929b664b6bc38f8b313e4b589e1efd
  symbols: config/GXSP8P-Demo/rels/ModelsKnuckles/symbols.txt
  splits: config/GXSP8P-Demo/rels/ModelsKnuckles/splits.txt
- object: orig/GXSP8P-Demo/files/Movie.rel
  hash: b8fee41215bcc03ad57142d56248fbbc1dfba891
  symbols: config/GXSP8P-Demo/rels/Movie/symbols.txt
  splits: config/GXSP8P-Demo/rels/Movie/splits.txt
- name: Stg01
  object: orig/GXSP8P-Demo/files/_Stg01.rel
  hash: 39cc1e58667c614e13395fa876f78c22ad903683
  symbols: config/GXSP8P-Demo/rels/Stg01/symbols.txt
  splits: config/GXSP8P-Demo/rels/Stg01/splits.txt
- name: Stg02
  object: orig/GXSP8P-Demo/files/_Stg02.rel
  hash: ef1779c35ddea7b9ea63fc91b3d8f44eff667cb1
  symbols: config/GXSP8P-Demo/rels/Stg02/symbols.txt
  splits: config/GXSP8P-Demo/rels/Stg02/splits.txt
- name: Stg04
  object: orig/GXSP8P-Demo/files/_Stg04.rel
  hash: 7542c58fb175ad7045653ed2f9a76992b0221af2
  symbols: config/GXSP8P-Demo/rels/Stg04/symbols.txt
  splits: config/GXSP8P-Demo/rels/Stg04/splits.txt
- name: Stg05
  object: orig/GXSP8P-Demo/files/_Stg05.rel
  hash: 77821d0254e6f74ddf6d6ebd0c6772d8939c7acd
  symbols: config/GXSP8P-Demo/rels/Stg05/symbols.txt
  splits: config/GXSP8P-Demo/rels/Stg05/splits.txt
- name: Stg08
  object: orig/GXSP8P-Demo/files/_Stg08.rel
  hash: 05e72bcab3dd8f0ada8b5295420345d8e57da625
  symbols: config/GXSP8P-Demo/rels/Stg08/symbols.txt
  splits: config/GXSP8P-Demo/rels/Stg08/splits.txt
- name: Stg10
  object: orig/GXSP8P-Demo/files/_Stg10.rel
  hash: 3be15b0dc73237d3ddec117a63a5f849747a1cd8
  symbols: config/GXSP8P-Demo/rels/Stg10/symbols.txt
  splits: config/GXSP8P-Demo/rels/Stg10/splits.txt
- object: orig/GXSP8P-Demo/files/summary.rel
  hash: a1ff14c0340e387509e13c2d7b73b1f8fbd7bf2a
  symbols: config/GXSP8P-Demo/rels/summary/symbols.txt
  splits: config/GXSP8P-Demo/rels/summary/splits.txt
- object: orig/GXSP8P-Demo/files/a_mot.rel
  hash: ba7dd5be6403dfe01f2e88037c20b56d8af368a6
  symbols: config/GXSP8P-Demo/rels/a_mot/symbols.txt
  splits: config/GXSP8P-Demo/rels/a_mot/splits.txt
- object: orig/GXSP8P-Demo/files/b_mot.rel
  hash: 5eeb03bddc615ae052cb09161cf6304a62b81e4e
  symbols: config/GXSP8P-Demo/rels/b_mot/symbols.txt
  splits: config/GXSP8P-Demo/rels/b_mot/splits.txt
- object: orig/GXSP8P-Demo/files/e_mot.rel
  hash: c21b6718432f7b5ff4c5d401ef61149d769adaa0
  symbols: config/GXSP8P-Demo/rels/e_mot/symbols.txt
  splits: config/GXSP8P-Demo/rels/e_mot/splits.txt
- object: orig/GXSP8P-Demo/files/k_mot.rel
  hash: 4e80226c9fc8b1fdf4cc04e4b3618c5754fdafd3
  symbols: config/GXSP8P-Demo/rels/k_mot/symbols.txt
  splits: config/GXSP8P-Demo/rels/k_mot/splits.txt
- object: orig/GXSP8P-Demo/files/s_mot.rel
  hash: 4a2712638106540f4f7802b34cead5fc3ec03679
  symbols: config/GXSP8P-Demo/rels/s_mot/symbols.txt
  splits: config/GXSP8P-Demo/rels/s_mot/splits.txt
- object: orig/GXSP8P-Demo/files/s_sbmot.rel
  hash: e2a6d368bdc0dab72385a34cfa086ae7318602a3
  symbols: config/GXSP8P-Demo/rels/s_sbmot/symbols.txt
  splits: config/GXSP8P-Demo/rels/s_sbmot/splits.txt
- object: orig/GXSP8P-Demo/files/m_sbmot.rel
  hash: 4f580aff9205a7ddf5df2390c50ea8410b24caf4
  symbols: config/GXSP8P-Demo/rels/m_sbmot/symbols.txt
  splits: config/GXSP8P-Demo/rels/m_sbmot/splits.txt
- object: orig/GXSP8P-Demo/files/Advertise.rel
  hash: 4ff7d20db4ac4df4802090d962f75494f25294ea
  symbols: config/GXSP8P-Demo/rels/Advertise/symbols.txt
  splits: config/GXSP8P-Demo/rels/Advertise/splits.txt
- object: orig/GXSP8P-Demo/files/alertwnd.rel
  hash: 26f66ce54558cb9949522d393547259b1237fc0c
  symbols: config/GXSP8P-Demo/rels/alertwnd/symbols.txt
  splits: config/GXSP8P-Demo/rels/alertwnd/splits.txt
