object: orig/GASJ8P-Demo/sys/main.dol
hash: 314d2322d01512e0deff4e23ed387946dcce1f2e
symbols: config/GASJ8P-Demo/symbols.txt
splits: config/GASJ8P-Demo/splits.txt
mw_comment_version: 10 # GC Linker 2.0

modules:
- name: Main
  object: orig/GASJ8P-Demo/files/_Main.rel
  hash: 15cd2fc9d185ffabebd5f0bbab57f86d9d558b8c
  symbols: config/GASJ8P-Demo/rels/Main/symbols.txt
  splits: config/GASJ8P-Demo/rels/Main/splits.txt
- object: orig/GASJ8P-Demo/files/ModelsMiles.rel
  hash: a7f855ab9e2926ee5840a4c0d8239eaaf29774e6
  symbols: config/GASJ8P-Demo/rels/ModelsMiles/symbols.txt
  splits: config/GASJ8P-Demo/rels/ModelsMiles/splits.txt
- object: orig/GASJ8P-Demo/files/ModelsKnuckles.rel
  hash: 02b0ac1a4e929b664b6bc38f8b313e4b589e1efd
  symbols: config/GASJ8P-Demo/rels/ModelsKnuckles/symbols.txt
  splits: config/GASJ8P-Demo/rels/ModelsKnuckles/splits.txt
- object: orig/GASJ8P-Demo/files/Movie.rel
  hash: 13519879571f7ad022df6932ac6f6f7953f4f292
  symbols: config/GASJ8P-Demo/rels/Movie/symbols.txt
  splits: config/GASJ8P-Demo/rels/Movie/splits.txt
- name: Stg01
  object: orig/GASJ8P-Demo/files/_Stg01.rel
  hash: 0a1b04f935bb26ee7b69818f69ade5a1384c39ea
  symbols: config/GASJ8P-Demo/rels/Stg01/symbols.txt
  splits: config/GASJ8P-Demo/rels/Stg01/splits.txt
- name: Stg02
  object: orig/GASJ8P-Demo/files/_Stg02.rel
  hash: 03f2ab446c08d0dc980f5457e35d45d613bbf346
  symbols: config/GASJ8P-Demo/rels/Stg02/symbols.txt
  splits: config/GASJ8P-Demo/rels/Stg02/splits.txt
- name: Stg04
  object: orig/GASJ8P-Demo/files/_Stg04.rel
  hash: fedb175a923dc2ed99413ee813986bcca739acf0
  symbols: config/GASJ8P-Demo/rels/Stg04/symbols.txt
  splits: config/GASJ8P-Demo/rels/Stg04/splits.txt
- name: Stg05
  object: orig/GASJ8P-Demo/files/_Stg05.rel
  hash: 4860fd741e777206df06be2bd0d1f39992e48938
  symbols: config/GASJ8P-Demo/rels/Stg05/symbols.txt
  splits: config/GASJ8P-Demo/rels/Stg05/splits.txt
- name: Stg08
  object: orig/GASJ8P-Demo/files/_Stg08.rel
  hash: 7812992665e0bd094aedcb6c03a76089d7cb8b70
  symbols: config/GASJ8P-Demo/rels/Stg08/symbols.txt
  splits: config/GASJ8P-Demo/rels/Stg08/splits.txt
- name: Stg10
  object: orig/GASJ8P-Demo/files/_Stg10.rel
  hash: c82b86b8c1b3e469ba3e37516b3c07df77a90c05
  symbols: config/GASJ8P-Demo/rels/Stg10/symbols.txt
  splits: config/GASJ8P-Demo/rels/Stg10/splits.txt
- object: orig/GASJ8P-Demo/files/summary.rel
  hash: 27163900b5a1ecea5ead3002285cc41284596ec0
  symbols: config/GASJ8P-Demo/rels/summary/symbols.txt
  splits: config/GASJ8P-Demo/rels/summary/splits.txt
- object: orig/GASJ8P-Demo/files/a_mot.rel
  hash: ba7dd5be6403dfe01f2e88037c20b56d8af368a6
  symbols: config/GASJ8P-Demo/rels/a_mot/symbols.txt
  splits: config/GASJ8P-Demo/rels/a_mot/splits.txt
- object: orig/GASJ8P-Demo/files/b_mot.rel
  hash: 57e3eb6c93cf3f01807c696e225ba2286fb212bf
  symbols: config/GASJ8P-Demo/rels/b_mot/symbols.txt
  splits: config/GASJ8P-Demo/rels/b_mot/splits.txt
- object: orig/GASJ8P-Demo/files/e_mot.rel
  hash: c21b6718432f7b5ff4c5d401ef61149d769adaa0
  symbols: config/GASJ8P-Demo/rels/e_mot/symbols.txt
  splits: config/GASJ8P-Demo/rels/e_mot/splits.txt
- object: orig/GASJ8P-Demo/files/k_mot.rel
  hash: b319ad319b8fdc0e029430017562c14249ee0b7b
  symbols: config/GASJ8P-Demo/rels/k_mot/symbols.txt
  splits: config/GASJ8P-Demo/rels/k_mot/splits.txt
- object: orig/GASJ8P-Demo/files/s_mot.rel
  hash: 2367c31de60bc8cab7ad5b8d77502cabb2dfc3d0
  symbols: config/GASJ8P-Demo/rels/s_mot/symbols.txt
  splits: config/GASJ8P-Demo/rels/s_mot/splits.txt
- object: orig/GASJ8P-Demo/files/s_sbmot.rel
  hash: e2a6d368bdc0dab72385a34cfa086ae7318602a3
  symbols: config/GASJ8P-Demo/rels/s_sbmot/symbols.txt
  splits: config/GASJ8P-Demo/rels/s_sbmot/splits.txt
- object: orig/GASJ8P-Demo/files/m_sbmot.rel
  hash: 4f580aff9205a7ddf5df2390c50ea8410b24caf4
  symbols: config/GASJ8P-Demo/rels/m_sbmot/symbols.txt
  splits: config/GASJ8P-Demo/rels/m_sbmot/splits.txt
- object: orig/GASJ8P-Demo/files/Advertise.rel
  hash: 6610872efe6177a329d29582580439bdfb709981
  symbols: config/GASJ8P-Demo/rels/Advertise/symbols.txt
  splits: config/GASJ8P-Demo/rels/Advertise/splits.txt
- object: orig/GASJ8P-Demo/files/alertwnd.rel
  hash: dd964c5e3acbcb71d74702a0c0d5e7e35e94653a
  symbols: config/GASJ8P-Demo/rels/alertwnd/symbols.txt
  splits: config/GASJ8P-Demo/rels/alertwnd/splits.txt
